### ISSUE TITLE
[FEED]: https://vyckes.dev/feed/feed.xml

### ISSUE THREAD

**Issue by vycke** [murtuzaalisurti/freed#38]
Mention the feed url:

```js
{
    url: https://vyckes.dev/feed/feed.xml
}
```

**Comment by murtuzaalisurti** [comment]
Hi @vyckes, this feed looks good, are you willing to generate a PR for it? The contribution steps are mentioned here https://github.com/murtuzaalisurti/rssed/blob/netlify/README.md

**Comment by vycke** [comment]
https://github.com/murtuzaalisurti/rssed/pull/39 @murtuzaalisurti :)

**Comment by murtuzaalisurti** [comment]
closed by https://github.com/murtuzaalisurti/rssed/pull/39
