### ISSUE TITLE
[FEED]: Astro’s official blog

### ISSUE THREAD

**Issue by delucis** [murtuzaalisurti/freed#77]
### Feed URL

https://astro.build/rss.xml

### More Info

Cool project! The search feature is really nice to use.

**Comment by murtuzaalisurti** [comment]
closed by https://github.com/murtuzaalisurti/rssed/commit/ccf3f7a3312861251e6c0b02e0ba86ab560c2121, thanks @delucis

**Comment by delucis** [comment]
Woo! Thanks for adding it 🚀
